/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#283044",
        "surface-dim": "#d2d9f4",
        "inverse-on-surface": "#eef0ff",
        "on-tertiary-fixed-variant": "#004b73",
        "on-tertiary-fixed": "#001d31",
        "outline-variant": "#c0c9be",
        "on-background": "#131b2e",
        "surface": "#faf8ff",
        "surface-container-high": "#e2e7ff",
        "outline": "#717970",
        "error": "#ba1a1a",
        "surface-bright": "#faf8ff",
        "tertiary-fixed": "#cce5ff",
        "inverse-primary": "#96d5a3",
        "on-secondary": "#ffffff",
        "tertiary": "#003553",
        "on-secondary-fixed-variant": "#005049",
        "on-primary-fixed": "#00210d",
        "secondary": "#006a61",
        "on-primary-fixed-variant": "#12512c",
        "primary-container": "#14532d",
        "tertiary-container": "#004c75",
        "primary-fixed-dim": "#96d5a3",
        "surface-container": "#eaedff",
        "error-container": "#ffdad6",
        "surface-tint": "#2e6a41",
        "secondary-fixed-dim": "#6bd8cb",
        "background": "#faf8ff",
        "on-primary-container": "#87c695",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "surface-variant": "#dae2fd",
        "on-error": "#ffffff",
        "on-surface-variant": "#404941",
        "surface-container-highest": "#dae2fd",
        "on-secondary-fixed": "#00201d",
        "tertiary-fixed-dim": "#93ccff",
        "primary": "#003b1b",
        "primary-fixed": "#b1f2be",
        "on-surface": "#131b2e",
        "on-secondary-container": "#006f66",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#89f5e7",
        "surface-container-low": "#f2f3ff",
        "secondary-container": "#86f2e4",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#6cbeff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin": "2rem",
        "margin-mobile": "1rem",
        "gutter-mobile": "1rem",
        "space-xl": "2.5rem",
        "space-md": "1rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-lg": "1.5rem",
        "gutter": "1.5rem",
      },
      fontFamily: {
        "headline-xl": ["Plus Jakarta Sans"],
        "body-sm": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "headline-xl-mobile": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
        "label-lg": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "headline-xl": ["2.25rem", { lineHeight: "2.75rem", letterSpacing: "-0.025em", fontWeight: "700" }],
        "body-sm": ["0.75rem", { lineHeight: "1.125rem", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-lg": ["1rem", { lineHeight: "1.625rem", letterSpacing: "0", fontWeight: "400" }],
        "headline-md": ["1.25rem", { lineHeight: "1.75rem", letterSpacing: "-0.015em", fontWeight: "600" }],
        "label-md": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-sm": ["0.6875rem", { lineHeight: "0.875rem", letterSpacing: "0.04em", fontWeight: "700" }],
        "headline-sm": ["1.125rem", { lineHeight: "1.5rem", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["1.75rem", { lineHeight: "2.25rem", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["0.875rem", { lineHeight: "1.375rem", letterSpacing: "0", fontWeight: "400" }],
        "headline-xl-mobile": ["1.75rem", { lineHeight: "2.25rem", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg": ["3rem", { lineHeight: "3.5rem", letterSpacing: "-0.03em", fontWeight: "800" }],
        "label-lg": ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
